import type { TrendItem } from './types';

export const INITIAL_TRENDS: TrendItem[] = [
  {
    id: 1,
    nameKey: 'trends.style1.name',
    descKey: 'trends.style1.desc',
    image: '/trend-ojos.png',
    color: 'bg-orange-50',
    popularity: 86,
    createdAt: Date.UTC(2026, 0, 26, 9, 0, 0),
    gender: 'women',
    season: 'winter',
    style: 'street',
  },
  {
    id: 2,
    nameKey: 'trends.style2.name',
    descKey: 'trends.style2.desc',
    image: '/trend-notknowing.png',
    color: 'bg-blue-50',
    popularity: 79,
    createdAt: Date.UTC(2026, 0, 30, 12, 0, 0),
    gender: 'women',
    season: 'spring',
    style: 'dandy',
  },
  {
    id: 3,
    nameKey: 'trends.style3.name',
    descKey: 'trends.style3.desc',
    image: '/trend-newalrin.png',
    color: 'bg-stone-50',
    popularity: 95,
    createdAt: Date.UTC(2026, 1, 2, 18, 0, 0),
    gender: 'men',
    season: 'fall',
    style: 'formal',
  },
  {
    id: 4,
    nameKey: 'trends.style4.name',
    descKey: 'trends.style4.desc',
    image: '/trend-painpleasure.png',
    color: 'bg-green-50',
    popularity: 72,
    createdAt: Date.UTC(2026, 1, 5, 8, 0, 0),
    gender: 'men',
    season: 'summer',
    style: 'street',
  },
  {
    id: 5,
    nameKey: 'trends.style5.name',
    descKey: 'trends.style5.desc',
    image: '/trend-deinet.png',
    color: 'bg-pink-50',
    popularity: 88,
    createdAt: Date.UTC(2026, 1, 10, 15, 0, 0),
    gender: 'women',
    season: 'spring',
    style: 'formal',
  },
  {
    id: 6,
    nameKey: 'trends.style6.name',
    descKey: 'trends.style6.desc',
    image: '/black-puffer.jpg',
    color: 'bg-indigo-50',
    popularity: 91,
    createdAt: Date.UTC(2026, 1, 14, 21, 0, 0),
    gender: 'men',
    season: 'winter',
    style: 'dandy',
  },
];

export const TREND_TAG_KEYS = [
  'trends.tags.texture',
  'trends.tags.volume',
  'trends.tags.nostalgia',
  'trends.tags.fluidity',
];
