import type { Asset } from '@freestyle/contracts/domain-types';

export const demoClosetAssets: Asset[] = [
  {
    id: 'demo-knit-top',
    name: 'Demo Knit Top',
    imageSrc: '/assets/demo/demo-knit-top.svg',
    category: 'tops',
    source: 'inventory',
    brand: 'FreeStyle Demo',
    removedBackground: true,
    metadata: {
      sourceTitle: 'Built-in demo knit top',
      sourceBrand: 'FreeStyle Demo',
      originalSize: { width: 512, height: 768 },
      cutout: { removedBackground: true },
      measurements: {
        chestCm: 104,
        waistCm: 92,
        shoulderCm: 46,
        sleeveLengthCm: 63,
        lengthCm: 68,
        hemCm: 96,
      },
      fitProfile: {
        silhouette: 'regular',
        layer: 'mid',
        structure: 'soft',
        stretch: 0.34,
        drape: 0.58,
      },
      dominantColor: '#c3bbb0',
    },
  },
  {
    id: 'demo-field-jacket',
    name: 'Demo Field Jacket',
    imageSrc: '/assets/demo/demo-field-jacket.svg',
    category: 'outerwear',
    source: 'inventory',
    brand: 'FreeStyle Demo',
    removedBackground: true,
    metadata: {
      sourceTitle: 'Built-in demo field jacket',
      sourceBrand: 'FreeStyle Demo',
      originalSize: { width: 512, height: 768 },
      cutout: { removedBackground: true },
      measurements: {
        chestCm: 116,
        waistCm: 108,
        shoulderCm: 49,
        sleeveLengthCm: 65,
        lengthCm: 76,
        hemCm: 112,
      },
      fitProfile: {
        silhouette: 'relaxed',
        layer: 'outer',
        structure: 'structured',
        stretch: 0.12,
        drape: 0.4,
      },
      dominantColor: '#7d705f',
    },
  },
  {
    id: 'demo-wide-trouser',
    name: 'Demo Wide Trouser',
    imageSrc: '/assets/demo/demo-wide-trouser.svg',
    category: 'bottoms',
    source: 'inventory',
    brand: 'FreeStyle Demo',
    removedBackground: true,
    metadata: {
      sourceTitle: 'Built-in demo wide trouser',
      sourceBrand: 'FreeStyle Demo',
      originalSize: { width: 512, height: 768 },
      cutout: { removedBackground: true },
      measurements: {
        waistCm: 84,
        hipCm: 106,
        inseamCm: 79,
        lengthCm: 111,
        hemCm: 50,
      },
      fitProfile: {
        silhouette: 'relaxed',
        layer: 'base',
        structure: 'balanced',
        stretch: 0.18,
        drape: 0.62,
      },
      dominantColor: '#4a4d57',
    },
  },
  {
    id: 'demo-combat-boots',
    name: 'Demo Combat Boots',
    imageSrc: '/assets/demo/demo-combat-boots.svg',
    category: 'shoes',
    source: 'inventory',
    brand: 'FreeStyle Demo',
    removedBackground: true,
    metadata: {
      sourceTitle: 'Built-in demo combat boots',
      sourceBrand: 'FreeStyle Demo',
      originalSize: { width: 512, height: 384 },
      cutout: { removedBackground: true },
      measurements: {
        lengthCm: 31,
        hemCm: 15,
      },
      fitProfile: {
        silhouette: 'regular',
        layer: 'base',
        structure: 'structured',
        stretch: 0.05,
        drape: 0.12,
      },
      dominantColor: '#252322',
    },
  },
];

export const demoClosetActiveAssetIds = demoClosetAssets.map((asset) => asset.id);
export const defaultDemoClosetAssetId = demoClosetAssets[1]?.id ?? demoClosetAssets[0]?.id ?? '';
