'use client';

import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'ko' | 'en';
const LANGUAGE_STORAGE_KEY = 'freestyle:language';
const LANGUAGE_COOKIE_KEY = 'freestyle-language';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const readInitialLanguage = (initialLanguage?: Language): Language => {
    if (typeof window === 'undefined') {
        return initialLanguage ?? 'ko';
    }

    return initialLanguage ?? (window.navigator.language.toLowerCase().startsWith('ko') ? 'ko' : 'en');
};

const translations = {
    en: {
        // Header
        'nav.home': 'Home',
        'nav.studio': 'Studio',
        'nav.trends': 'Feed',
        'nav.community': 'Community',
        'nav.profile': 'Profile',
        'search.placeholder': 'Search assets...',

        // Home
        'hero.badge': 'FreeStyle Studio / Beta 1.0',
        'hero.title1': 'Create',
        'hero.title2': 'your',
        'hero.title3': 'style',
        'hero.desc': 'A digital atelier for modern curators.\nCombine pieces, get AI feedback, and curate your perfect look.',
        'hero.start': 'Open Studio',
        'hero.tryon': 'Explore Feed',
        'hero.marquee_alt1': 'Featured look 1',
        'hero.marquee_alt2': 'Featured look 2',
        'hero.marquee_alt3': 'Featured look 3',
        'footer.inc': 'FreeStyle Collective © 2026',
        'footer.vi': 'Visual Intelligence',
        'footer.sd': 'Sensory Design',
        'footer.gt': 'Global Trend Report',
        'footer.cities': 'Seoul • Paris • New York • Tokyo',

        // Studio / Builder
        'studio.title': 'Studio Builder',
        'studio.import_link': 'Import from link',
        'studio.import_image': 'Upload image',
        'studio.summary': 'Outfit Summary',
        'studio.subtotal': 'Estimated total',
        'studio.tryon_btn': 'AI Virtual Fitting',
        'studio.review_btn': 'AI Style Review',
        'studio.save': 'Save to archive',
        'studio.save.loading': 'Saving...',
        'studio.save.success': 'Share link created.',
        'studio.save.error': 'Failed to save the outfit.',
        'studio.save.default_title': 'Outfit',
        'studio.save.title': 'Save outfit',
        'studio.save.desc': 'Give this outfit a title so you can find it later.',
        'studio.save.name_label': 'Outfit name',
        'studio.save.name_placeholder': 'e.g. Minimal denim look',
        'studio.save.desc_label': 'Notes (optional)',
        'studio.save.desc_placeholder': 'Add a memo or styling tip',
        'studio.save.cta': 'Save',
        'studio.save.cancel': 'Cancel',
        'studio.save.name_required': 'Please enter a name.',
        'studio.share.copy': 'Copy link',
        'studio.share.copied': 'Copied',
        'studio.categories.all': 'All',
        'studio.categories.tops': 'Tops',
        'studio.categories.bottoms': 'Bottoms',
        'studio.categories.outerwear': 'Outerwear',
        'studio.categories.shoes': 'Shoes',
        'studio.categories.accessories': 'Accessories',
        'studio.categories.custom': 'Custom',
        'studio.modal.title': 'Virtual Fitting',
        'studio.modal.desc': 'Upload a full-body photo to preview a high-fidelity virtual fitting.',
        'studio.modal.upload': 'Upload photo',
        'studio.items_count': 'items',
        'studio.library': 'Asset Library',
        'studio.asset.badge.uploaded': 'Uploaded',
        'studio.asset.badge.imported': 'Imported',
        'studio.asset.badge.cutout': 'Cutout',
        'studio.asset.badge.original': 'Original',
        'studio.asset.delete': 'Delete asset',
        'studio.asset.delete_confirm': 'Delete this asset?',
        'studio.asset.delete_failed': 'Failed to delete asset.',
        'studio.asset.save_error': 'Could not save the asset.',
        'studio.asset.custom': 'Custom item',
        'studio.asset.imported': 'Imported item',
        'studio.asset.uploaded': 'Uploaded item',
        'studio.inventory.item1.name': 'Fluffy Earflap Cap',
        'studio.inventory.item2.name': 'Wild Faux Fur Hoodie',
        'studio.inventory.item3.name': 'Shearling Jacket',
        'studio.inventory.item4.name': 'Logo T-Shirt',
        'studio.inventory.item5.name': 'Leather Mini Skirt',
        'studio.inventory.item6.name': 'Rhea Bag',
        'studio.inventory.item7.name': 'Buckle Boots',
        'studio.trending_now': 'Trending now',
        'studio.mode': 'Studio mode',
        'studio.empty.title': 'Start your curation',
        'studio.empty.subtitle': 'The full archive is best viewed on desktop.',
        'studio.modal.cta': 'Quick preview',
        'studio.modal.alert': 'Preparing your virtual fitting with NanoBanana AI...',
        'studio.modal.powered_by': 'Powered by NanoBanana Sensory Engine v4.0',
        'studio.review.title': 'AI Outfit Review',
        'studio.review.desc': 'Get feedback on balance, mood, and silhouette based on your outfit.',
        'studio.review.placeholder': 'Generate a review to see insights and suggestions.',
        'studio.review.preview_label': 'Preview',
        'studio.review.preview_alt': 'Outfit preview',
        'studio.review.preview_empty': 'Generate a review to capture the preview.',
        'studio.review.loading': 'Reviewing...',
        'studio.review.loading_title': 'Analyzing your outfit',
        'studio.review.loading_desc': 'Checking silhouette, balance, and color harmony. Just a moment.',
        'studio.review.feedback_title': 'AI Feedback',
        'studio.review.score': 'Overall score',
        'studio.review.items': 'Item breakdown',
        'studio.review.mood': 'Mood',
        'studio.review.silhouette': 'Silhouette',
        'studio.review.balance': 'Balance',
        'studio.review.palette': 'Palette',
        'studio.review.fit': 'Fit',
        'studio.review.color': 'Color harmony',
        'studio.review.strengths': 'Strengths',
        'studio.review.improvements': 'Improvements',
        'studio.review.occasions': 'Best occasions',
        'studio.review.summary': 'Summary',
        'studio.review.error_generic': 'Could not generate the review.',
        'studio.review.error_image': 'Could not load the preview image.',
        'studio.review.error_required': 'Please select gender and occasion first.',
        'studio.review.gender_label': 'Gender',
        'studio.review.gender_female': 'Female',
        'studio.review.gender_male': 'Male',
        'studio.review.gender_nonbinary': 'Non-binary',
        'studio.review.occasion_label': 'Occasion',
        'studio.review.occasion_daily': 'Daily',
        'studio.review.occasion_work': 'Work',
        'studio.review.occasion_date': 'Date',
        'studio.review.occasion_travel': 'Travel',
        'studio.review.occasion_formal': 'Formal',
        'studio.review.occasion_party': 'Party',
        'studio.review.occasion_custom': 'Custom',
        'studio.review.occasion_placeholder': 'Describe the occasion',
        'studio.review.personal_color_label': 'Personal color',
        'studio.review.personal_color_optional': 'Optional',
        'studio.review.personal_color_spring': 'Spring warm',
        'studio.review.personal_color_summer': 'Summer cool',
        'studio.review.personal_color_autumn': 'Autumn warm',
        'studio.review.personal_color_winter': 'Winter cool',
        'studio.review.personal_color_neutral': 'Neutral',
        'studio.review.select_placeholder': 'Select',
        'studio.review.close': 'Close',
        'studio.review.cta': 'Start review',
        'studio.review.disabled': 'Connect AI to enable.',
        'studio.vto.cta': 'AI try-on',
        'studio.vto.loading': 'Generating...',
        'studio.vto.error_generic': 'AI try-on failed.',
        'studio.vto.timeout': 'AI try-on is taking longer than expected.',
        'studio.job.processing': 'Removing the background...',
        'studio.job.failed': 'Background removal failed.',
        'studio.job.missing_key': 'Background removal API key is missing.',
        'studio.job.timeout': 'Processing is taking longer than expected.',
        'studio.import.title': 'Import from link',
        'studio.import.desc': 'Paste a product link. We will find the main image and cut out the background.',
        'studio.import.url_label': 'Product URL',
        'studio.import.url_placeholder': 'https://',
        'studio.import.name_label': 'Item name',
        'studio.import.name_placeholder': 'Name this piece',
        'studio.import.category_label': 'Category',
        'studio.import.cta': 'Create asset',
        'studio.import.cancel': 'Cancel',
        'studio.import.loading': 'Processing...',
        'studio.import.error_url': 'Please paste a valid URL.',
        'studio.import.error_generic': 'Could not import the image. Try another link.',
        'studio.import.notice_no_bg': 'Background removal failed. Using the original image.',
        'studio.import.candidate.title': 'Pick the product-only image',
        'studio.import.candidate.desc': 'Automatic detection failed. Select the best standalone front shot.',
        'studio.import.candidate.cta': 'Use selected image',
        'studio.import.candidate.model_hint': 'Model-like detected',
        'studio.import.candidate.product_hint': 'Likely standalone product',
        'studio.cart_import.button': 'Cart',
        'studio.cart_import.title': 'Import from cart link',
        'studio.cart_import.desc': 'Paste a shopping cart URL and import product assets in bulk.',
        'studio.cart_import.url_label': 'Cart URL',
        'studio.cart_import.cta': 'Import cart',
        'studio.cart_import.loading': 'Importing cart...',
        'studio.cart_import.error_generic': 'Could not import products from this cart link.',
        'studio.cart_import.imported_suffix': ' products imported.',
        'studio.cart_import.failed_suffix': ' products failed.',
        'studio.bridge.title': 'Import from Musinsa bridge',
        'studio.bridge.desc':
          'A browser helper captured product URLs from Musinsa. Review the list, choose a category, then import them into Studio.',
        'studio.bridge.captured_from': 'Captured from',
        'studio.bridge.count_label': 'Products',
        'studio.bridge.captured_at': 'Captured at',
        'studio.bridge.cta': 'Import selected products',
        'studio.bridge.loading': 'Importing Musinsa products...',
        'studio.bridge.error_generic': 'Could not import products from the Musinsa bridge.',
        'studio.bridge.helper_title': 'Use the Musinsa helper script',
        'studio.bridge.helper_desc':
          'Run the userscript on a Musinsa page to open this screen with the captured product URLs.',
        'studio.bridge.total_hint': 'The bridge reuses the existing async product import pipeline.',
        'studio.bridge.imported_suffix': ' products imported.',
        'studio.bridge.failed_suffix': ' products failed.',
        'studio.upload.title': 'Upload image',
        'studio.upload.desc': 'Upload a clothing photo and we will cut out the background.',
        'studio.upload.file_label': 'Image file',
        'studio.upload.drop': 'Drop or click to upload',
        'studio.upload.preview_alt': 'Uploaded preview',
        'studio.upload.name_label': 'Item name',
        'studio.upload.name_placeholder': 'Name this piece',
        'studio.upload.category_label': 'Category',
        'studio.upload.cta': 'Create asset',
        'studio.upload.cancel': 'Cancel',
        'studio.upload.loading': 'Processing...',
        'studio.upload.error_file': 'Choose an image to upload.',
        'studio.upload.error_generic': 'Could not process the image.',
        'studio.upload.notice_no_bg': 'Background removal failed. Using the original image.',
        'studio.asset.link.open': 'Open product link',
        'studio.price.custom': 'Custom',
        'studio.model.alt': 'Model photo',
        'studio.tryon.upload_label': 'Model photo',
        'studio.tryon.saved': 'Saved for this device',
        'studio.tryon.loading': 'Generating...',
        'studio.tryon.preview_label': 'Preview',
        'studio.tryon.preview_empty': 'Generate a try-on preview to see the result.',
        'studio.tryon.preview_alt': 'Try-on preview',
        'studio.tryon.download': 'Download image',
        'studio.tryon.error_generic': 'Could not generate the try-on image.',
        'studio.tryon.error_no_model': 'Upload a model photo first.',
        'studio.tryon.error_no_items': 'Add items to the canvas first.',
        'studio.canvas_size': 'Canvas size',
        'studio.add_text': 'Add text',
        'studio.download': 'Download as image',
        'studio.text.title': 'Add Text',
        'studio.text.desc': 'Add custom text to your canvas.',
        'studio.text.content': 'Text content',
        'studio.text.placeholder': 'Type your text here...',
        'studio.text.color': 'Color',
        'studio.text.size': 'Size',
        'studio.text.preview': 'Preview',
        'studio.text.cancel': 'Cancel',
        'studio.text.add': 'Add to canvas',

        // Trends
        'trends.badge': 'Real-time stream',
        'trends.title': 'Trend',
        'trends.title1': 'Trend',
        'trends.title2': 'Archive',
        'trends.sort.popular': 'Popular',
        'trends.sort.latest': 'Latest',
        'trends.filter.all': 'All',
        'trends.filter.gender': 'Gender',
        'trends.filter.gender.men': 'Men',
        'trends.filter.gender.women': 'Women',
        'trends.filter.season': 'Season',
        'trends.filter.season.spring': 'Spring',
        'trends.filter.season.summer': 'Summer',
        'trends.filter.season.fall': 'Fall',
        'trends.filter.season.winter': 'Winter',
        'trends.filter.style': 'Style',
        'trends.filter.style.street': 'Street',
        'trends.filter.style.formal': 'Formal',
        'trends.filter.style.dandy': 'Dandy',
        'trends.filter.empty': 'No feed items match this filter.',
        'trends.detail.creator': 'Creator',
        'trends.detail.outfit': 'Outfit Name',
        'trends.detail.category': 'Category',
        'trends.detail.description': 'Description',
        'trends.desc': 'A curated stream of global visual culture and emerging subcultures.',
        'trends.popup.title': 'Editorial insight',
        'trends.popup.close': 'Close',
        'trends.style1.name': 'Urban Grunge',
        'trends.style1.desc': 'A raw reinterpretation of 90s alternative silhouettes. Distressed textures, oversized layering, and deliberate imperfection.',
        'trends.style2.name': 'Neo Cyber',
        'trends.style2.desc': 'High-performance technical gear meets futuristic urban aesthetics. Defined by synthetic materials and modular function.',
        'trends.style3.name': 'Quiet Luxury',
        'trends.style3.desc': 'Understated elegance. Premium fabrication and precise tailoring shape a timeless silhouette.',
        'trends.style4.name': 'Gorpcore 2.0',
        'trends.style4.desc': 'Outdoor engineering repurposed for the city. Technical performance fused with curated fashion.',
        'trends.style5.name': 'Ethereal Core',
        'trends.style5.desc': 'A soft blend of athleticism and fluid form. Ribbon details, wrap silhouettes, and airy palettes.',
        'trends.style6.name': 'Modern Heritage',
        'trends.style6.desc': 'Classic tailoring reimagined for today. Sharp lines and heritage fabrics with a fresh edge.',
        'trends.velocity': 'Analyzing global data streams...',
        'trends.alt.card': 'Trend look',
        'trends.alt.editorial': 'Editorial visual',
        'trends.meta.archive_prefix': 'Visual Intelligence Archive',
        'trends.tags.texture': 'Texture',
        'trends.tags.volume': 'Volume',
        'trends.tags.nostalgia': 'Nostalgia',
        'trends.tags.fluidity': 'Fluidity',
        'trends.meta.popularity_label': 'Popularity',
        'trends.meta.popularity_value': 'High',
        'trends.meta.context_label': 'Context',
        'trends.meta.context_value': 'Aesthetic',
        'trends.cta.explore': 'Explore collection',

        // Community
        'community.title_bg': 'Collective',
        'community.title': 'The Circle',
        'community.desc': 'A global network of curators and creators sharing visual inspiration.',
        'community.share': 'Share your style',
        'community.follow': 'Follow',
        'community.post_desc': 'Exploring the intersection of digital texture and organic silhouettes.',
        'community.stat1': 'Curators',
        'community.stat2': 'Looks shared',
        'community.stat3': 'Global hubs',
        'community.stat4': 'Status',
        'community.filters.all': 'All posts',
        'community.filters.trending': 'Trending',
        'community.filters.following': 'Following',
        'community.filters.atelier': 'Digital atelier',
        'community.filters.subculture': 'Neo-subculture',
        'community.contributor': 'Contributor',
        'community.alt.look': 'Community look',
        'community.stat3.value': 'Seoul',
        'community.stat4.value': 'Live',
        'community.tags.cyber': 'Cyber',
        'community.tags.tech': 'Tech',
        'community.tags.vintage': 'Vintage',
        'community.tags.minimal': 'Minimal',
        'community.tags.tailoring': 'Tailoring',
        'community.tags.neo': 'Neo',
        'community.tags.utility': 'Utility',
        'community.tags.outdoor': 'Outdoor',
        'community.tags.abstract': 'Abstract',
        'community.tags.ethereal': 'Ethereal',
        'community.tags.monochrome': 'Monochrome',
        'community.tags.avant': 'Avant',
        'community.tags.layering': 'Layering',
        'community.tags.urban': 'Urban',
        'community.tags.core': 'Core',
        'community.tags.future': 'Future',
        'community.tags.graphic': 'Graphic',
        'community.tags.street': 'Street',

        // Profile
        'profile.settings': 'Editorial settings',
        'profile.node': 'Private archive node 042',
        'profile.stat.reach': 'Reach',
        'profile.stat.curation': 'Curation',
        'profile.stat.assets': 'Assets',
        'profile.stat.archive': 'Archive',
        'profile.header.badge': 'FreeStyle Profile',
        'profile.header.title': 'My Archive',
        'profile.header.subtitle': 'Curate, save, and share your outfits.',
        'profile.bio.line1': 'Exploring the intersection of digital craft and physical form.',
        'profile.bio.line2_prefix': 'Specializing in',
        'profile.bio.line2_connector': 'and',
        'profile.bio.line2_suffix': 'aesthetics.',
        'profile.bio.focus1': 'Urban Grunge',
        'profile.bio.focus2': 'Neo Cyber',
        'profile.tabs.archived': 'Archived',
        'profile.tabs.curations': 'My curations',
        'profile.tabs.saved': 'Saved assets',
        'profile.post.view_asset': 'View asset',
        'profile.post.node': 'Visual Archive Node // 2026',
        'profile.post.title_prefix': 'Archive',
        'profile.alt.avatar': 'Profile photo',
        'profile.archive.label': 'Archive',
        'profile.empty.archive': 'No outfits saved yet.',
        'profile.empty.assets': 'No assets saved yet.',
        'profile.delete': 'Delete',
        'profile.share.copy': 'Copy link',
        'profile.share.copied': 'Copied',
        'profile.search.archive_placeholder': 'Search outfits by name',
        'profile.search.asset_placeholder': 'Search assets by name',
        'profile.filter.all': 'All categories',
    },
    ko: {
        // Header
        'nav.home': '홈',
        'nav.studio': '스튜디오',
        'nav.trends': '피드',
        'nav.community': '커뮤니티',
        'nav.profile': '프로필',
        'search.placeholder': '에셋을 검색하세요...',

        // Home
        'hero.badge': 'FreeStyle Studio / 베타 1.0',
        'hero.title1': '나만의',
        'hero.title2': '스타일을',
        'hero.title3': '완성하세요',
        'hero.desc': '현대적 큐레이터를 위한 디지털 아틀리에.\n아이템을 조합하고, AI 피드백을 받아 완벽한 룩을 만들어보세요.',
        'hero.start': '스튜디오 열기',
        'hero.tryon': '피드 탐색',
        'hero.marquee_alt1': '대표 룩 1',
        'hero.marquee_alt2': '대표 룩 2',
        'hero.marquee_alt3': '대표 룩 3',
        'footer.inc': 'FreeStyle Collective © 2026',
        'footer.vi': '비주얼 인텔리전스',
        'footer.sd': '감각적 디자인',
        'footer.gt': '글로벌 트렌드 리포트',
        'footer.cities': '서울 • 파리 • 뉴욕 • 도쿄',

        // Studio / Builder
        'studio.title': '스튜디오 빌더',
        'studio.import_link': '링크에서 가져오기',
        'studio.import_image': '이미지 업로드',
        'studio.summary': '코디 요약',
        'studio.subtotal': '예상 합계',
        'studio.tryon_btn': 'AI 가상 피팅',
        'studio.review_btn': 'AI 평가받기',
        'studio.save': '아카이브에 저장',
        'studio.save.loading': '저장 중...',
        'studio.save.success': '공유 링크가 생성됐어요.',
        'studio.save.error': '코디를 저장하지 못했어요.',
        'studio.save.default_title': '코디',
        'studio.save.title': '코디 저장',
        'studio.save.desc': '나중에 찾기 쉽게 이름을 입력해주세요.',
        'studio.save.name_label': '코디 이름',
        'studio.save.name_placeholder': '예: 미니멀 데님 룩',
        'studio.save.desc_label': '메모 (선택)',
        'studio.save.desc_placeholder': '스타일링 팁을 적어보세요',
        'studio.save.cta': '저장하기',
        'studio.save.cancel': '취소',
        'studio.save.name_required': '이름을 입력해주세요.',
        'studio.share.copy': '링크 복사',
        'studio.share.copied': '복사됨',
        'studio.categories.all': '전체',
        'studio.categories.tops': '상의',
        'studio.categories.bottoms': '하의',
        'studio.categories.outerwear': '아우터',
        'studio.categories.shoes': '슈즈',
        'studio.categories.accessories': '액세서리',
        'studio.categories.custom': '커스텀',
        'studio.modal.title': '가상 피팅',
        'studio.modal.desc': '전신 사진을 업로드하면 고해상도 가상 피팅을 미리 볼 수 있어요.',
        'studio.modal.upload': '사진 업로드',
        'studio.items_count': '개',
        'studio.library': '에셋 라이브러리',
        'studio.asset.badge.uploaded': '업로드',
        'studio.asset.badge.imported': '링크',
        'studio.asset.badge.cutout': '누끼',
        'studio.asset.badge.original': '원본',
        'studio.asset.delete': '에셋 삭제',
        'studio.asset.delete_confirm': '이 에셋을 삭제할까요?',
        'studio.asset.delete_failed': '에셋 삭제에 실패했어요.',
        'studio.asset.save_error': '에셋을 저장하지 못했어요.',
        'studio.asset.custom': '커스텀 아이템',
        'studio.asset.imported': '링크 아이템',
        'studio.asset.uploaded': '업로드 아이템',
        'studio.inventory.item1.name': '플러피 이어플랩 캡',
        'studio.inventory.item2.name': '와일드 페이크 퍼 후디',
        'studio.inventory.item3.name': '시어링 재킷',
        'studio.inventory.item4.name': '로고 티셔츠',
        'studio.inventory.item5.name': '레더 미니 스커트',
        'studio.inventory.item6.name': '레아 백',
        'studio.inventory.item7.name': '버클 부츠',
        'studio.trending_now': '지금 인기',
        'studio.mode': '스튜디오 모드',
        'studio.empty.title': '스타일을 담아보세요',
        'studio.empty.subtitle': '전체 아카이브는 데스크톱에서 더 잘 보입니다.',
        'studio.modal.cta': '빠른 미리보기',
        'studio.modal.alert': 'NanoBanana AI로 가상 피팅을 준비 중이에요...',
        'studio.modal.powered_by': 'NanoBanana Sensory Engine v4.0 기반',
        'studio.review.title': 'AI 코디 평가',
        'studio.review.desc': '코디의 균형, 무드, 실루엣을 분석해 피드백을 제공합니다.',
        'studio.review.placeholder': '평가를 생성하면 점수와 개선 제안이 표시됩니다.',
        'studio.review.preview_label': '프리뷰',
        'studio.review.preview_alt': '코디 프리뷰',
        'studio.review.preview_empty': '평가를 시작하면 프리뷰가 캡처됩니다.',
        'studio.review.loading': '평가 중...',
        'studio.review.loading_title': '코디 분석 중이에요',
        'studio.review.loading_desc': '실루엣과 컬러 밸런스를 살펴보고 있어요. 잠시만 기다려주세요.',
        'studio.review.feedback_title': 'AI 피드백',
        'studio.review.score': '종합 점수',
        'studio.review.items': '아이템 분석',
        'studio.review.mood': '무드',
        'studio.review.silhouette': '실루엣',
        'studio.review.balance': '밸런스',
        'studio.review.palette': '컬러 팔레트',
        'studio.review.fit': '핏',
        'studio.review.color': '색 조합',
        'studio.review.strengths': '장점',
        'studio.review.improvements': '개선 포인트',
        'studio.review.occasions': '어울리는 상황',
        'studio.review.summary': '요약',
        'studio.review.error_generic': '평가를 만들지 못했어요.',
        'studio.review.error_image': '프리뷰 이미지를 불러오지 못했어요.',
        'studio.review.error_required': '성별과 상황을 선택해주세요.',
        'studio.review.gender_label': '성별',
        'studio.review.gender_female': '여성',
        'studio.review.gender_male': '남성',
        'studio.review.gender_nonbinary': '논바이너리',
        'studio.review.occasion_label': '상황',
        'studio.review.occasion_daily': '데일리',
        'studio.review.occasion_work': '출근/업무',
        'studio.review.occasion_date': '데이트',
        'studio.review.occasion_travel': '여행',
        'studio.review.occasion_formal': '격식',
        'studio.review.occasion_party': '파티',
        'studio.review.occasion_custom': '직접 입력',
        'studio.review.occasion_placeholder': '상황을 직접 입력해주세요',
        'studio.review.personal_color_label': '퍼스널 컬러',
        'studio.review.personal_color_optional': '선택 사항',
        'studio.review.personal_color_spring': '봄 웜',
        'studio.review.personal_color_summer': '여름 쿨',
        'studio.review.personal_color_autumn': '가을 웜',
        'studio.review.personal_color_winter': '겨울 쿨',
        'studio.review.personal_color_neutral': '뉴트럴',
        'studio.review.select_placeholder': '선택',
        'studio.review.close': '닫기',
        'studio.review.cta': '평가 시작',
        'studio.review.disabled': 'AI 연동 후 사용 가능',
        'studio.vto.cta': 'AI 가상 피팅',
        'studio.vto.loading': '생성 중...',
        'studio.vto.error_generic': 'AI 가상 피팅에 실패했어요.',
        'studio.vto.timeout': '가상 피팅이 예상보다 오래 걸리고 있어요.',
        'studio.job.processing': '배경을 제거하는 중이에요...',
        'studio.job.failed': '배경 제거에 실패했어요.',
        'studio.job.missing_key': '배경 제거 API 키가 없어요.',
        'studio.job.timeout': '처리가 예상보다 오래 걸리고 있어요.',
        'studio.import.title': '링크에서 가져오기',
        'studio.import.desc': '상품 링크를 붙여넣으면 대표 이미지를 찾고 배경을 제거해요.',
        'studio.import.url_label': '상품 링크',
        'studio.import.url_placeholder': 'https://',
        'studio.import.name_label': '아이템 이름',
        'studio.import.name_placeholder': '아이템을 이름으로 저장',
        'studio.import.category_label': '카테고리',
        'studio.import.cta': '에셋 생성',
        'studio.import.cancel': '취소',
        'studio.import.loading': '처리 중...',
        'studio.import.error_url': '유효한 링크를 입력해주세요.',
        'studio.import.error_generic': '이미지를 가져오지 못했어요. 다른 링크로 시도해 주세요.',
        'studio.import.notice_no_bg': '배경 제거에 실패해 원본 이미지를 사용합니다.',
        'studio.import.candidate.title': '상품 단독컷을 선택해주세요',
        'studio.import.candidate.desc': '자동 탐지에 실패했어요. 후보 중 가장 적절한 정면 단독컷을 골라주세요.',
        'studio.import.candidate.cta': '선택한 이미지로 가져오기',
        'studio.import.candidate.model_hint': '모델컷으로 감지됨',
        'studio.import.candidate.product_hint': '단독 상품컷 가능성 높음',
        'studio.cart_import.button': '장바구니',
        'studio.cart_import.title': '장바구니 링크 가져오기',
        'studio.cart_import.desc': '쇼핑 플랫폼 장바구니 링크를 붙여넣으면 상품 이미지를 일괄 등록합니다.',
        'studio.cart_import.url_label': '장바구니 링크',
        'studio.cart_import.cta': '일괄 가져오기',
        'studio.cart_import.loading': '장바구니 분석 중...',
        'studio.cart_import.error_generic': '장바구니 링크에서 상품을 가져오지 못했어요.',
        'studio.cart_import.imported_suffix': '개 등록,',
        'studio.cart_import.failed_suffix': '개 실패',
        'studio.bridge.title': '무신사 브리지에서 가져오기',
        'studio.bridge.desc':
          '브라우저 도우미가 무신사 페이지에서 상품 링크를 가져왔어요. 목록을 확인하고 카테고리를 고른 뒤 Studio로 가져오세요.',
        'studio.bridge.captured_from': '캡처한 페이지',
        'studio.bridge.count_label': '상품 수',
        'studio.bridge.captured_at': '캡처 시각',
        'studio.bridge.cta': '선택한 상품 가져오기',
        'studio.bridge.loading': '무신사 상품 가져오는 중...',
        'studio.bridge.error_generic': '무신사 브리지에서 상품을 가져오지 못했어요.',
        'studio.bridge.helper_title': '무신사 도우미 스크립트 사용',
        'studio.bridge.helper_desc':
          '무신사 페이지에서 유저스크립트를 실행하면 캡처한 상품 링크와 함께 이 화면이 열립니다.',
        'studio.bridge.total_hint': '브리지는 기존 비동기 상품 임포트 파이프라인을 그대로 재사용합니다.',
        'studio.bridge.imported_suffix': '개 등록,',
        'studio.bridge.failed_suffix': '개 실패',
        'studio.upload.title': '이미지 업로드',
        'studio.upload.desc': '옷 사진을 업로드하면 배경을 자동으로 제거합니다.',
        'studio.upload.file_label': '이미지 파일',
        'studio.upload.drop': '파일을 끌어놓거나 클릭하세요',
        'studio.upload.preview_alt': '업로드 미리보기',
        'studio.upload.name_label': '아이템 이름',
        'studio.upload.name_placeholder': '아이템 이름 입력',
        'studio.upload.category_label': '카테고리',
        'studio.upload.cta': '에셋 생성',
        'studio.upload.cancel': '취소',
        'studio.upload.loading': '처리 중...',
        'studio.upload.error_file': '업로드할 이미지를 선택해주세요.',
        'studio.upload.error_generic': '이미지 처리를 완료하지 못했어요.',
        'studio.upload.notice_no_bg': '배경 제거에 실패해 원본 이미지를 사용합니다.',
        'studio.asset.link.open': '상품 링크 열기',
        'studio.price.custom': '커스텀',
        'studio.model.alt': '모델 사진',
        'studio.tryon.upload_label': '모델 사진',
        'studio.tryon.saved': '이 기기에 저장됨',
        'studio.tryon.loading': '생성 중...',
        'studio.tryon.preview_label': '미리보기',
        'studio.tryon.preview_empty': '입어보기 프리뷰를 생성해 보세요.',
        'studio.tryon.preview_alt': '입어보기 미리보기',
        'studio.tryon.download': '이미지 다운로드',
        'studio.tryon.error_generic': '입어보기 이미지를 만들지 못했어요.',
        'studio.tryon.error_no_model': '먼저 모델 사진을 업로드해주세요.',
        'studio.tryon.error_no_items': '먼저 캔버스에 아이템을 배치해주세요.',
        'studio.canvas_size': '캔버스 크기',
        'studio.add_text': '텍스트 추가',
        'studio.download': '이미지로 다운로드',
        'studio.text.title': '텍스트 추가',
        'studio.text.desc': '캔버스에 텍스트를 추가하세요.',
        'studio.text.content': '텍스트 내용',
        'studio.text.placeholder': '여기에 텍스트를 입력하세요...',
        'studio.text.color': '색상',
        'studio.text.size': '크기',
        'studio.text.preview': '미리보기',
        'studio.text.cancel': '취소',
        'studio.text.add': '캔버스에 추가',

        // Trends
        'trends.badge': '실시간 스트림',
        'trends.title': '트렌드',
        'trends.title1': '트렌드',
        'trends.title2': '아카이브',
        'trends.sort.popular': '인기순',
        'trends.sort.latest': '최신순',
        'trends.filter.all': '전체',
        'trends.filter.gender': '성별',
        'trends.filter.gender.men': '남',
        'trends.filter.gender.women': '여',
        'trends.filter.season': '계절',
        'trends.filter.season.spring': '봄',
        'trends.filter.season.summer': '여름',
        'trends.filter.season.fall': '가을',
        'trends.filter.season.winter': '겨울',
        'trends.filter.style': '스타일',
        'trends.filter.style.street': '스트릿',
        'trends.filter.style.formal': '포멀',
        'trends.filter.style.dandy': '댄디',
        'trends.filter.empty': '조건에 맞는 피드가 없습니다.',
        'trends.detail.creator': '코디 제작자',
        'trends.detail.outfit': '코디 이름',
        'trends.detail.category': '카테고리',
        'trends.detail.description': '설명',
        'trends.desc': '글로벌 비주얼 컬처와 새롭게 떠오르는 서브컬처를 큐레이션합니다.',
        'trends.popup.title': '에디토리얼 인사이트',
        'trends.popup.close': '닫기',
        'trends.style1.name': '어반 그런지',
        'trends.style1.desc': '90년대 얼터너티브 실루엣을 거칠게 재해석한 스타일. 디스트레스 텍스처와 오버사이즈 레이어링이 특징입니다.',
        'trends.style2.name': '네오 사이버',
        'trends.style2.desc': '고성능 테크웨어와 미래적 어반 미학의 만남. 합성 소재와 모듈형 기능이 돋보입니다.',
        'trends.style3.name': '콰이어트 럭셔리',
        'trends.style3.desc': '절제된 우아함. 고급 소재와 정교한 테일러링으로 타임리스 실루엣을 완성합니다.',
        'trends.style4.name': '고프코어 2.0',
        'trends.style4.desc': '도심을 위한 아웃도어 엔지니어링. 기술적 성능과 하이패션 감각의 결합.',
        'trends.style5.name': '에테리얼 코어',
        'trends.style5.desc': '부드러운 실루엣과 유려한 움직임의 조화. 리본 디테일과 랩 실루엣, 은은한 팔레트가 특징입니다.',
        'trends.style6.name': '모던 헤리티지',
        'trends.style6.desc': '클래식 테일러링을 현대적으로 재해석. 날카로운 라인과 헤리티지 원단이 조화를 이룹니다.',
        'trends.velocity': '글로벌 데이터 스트림 분석 중...',
        'trends.alt.card': '트렌드 룩',
        'trends.alt.editorial': '에디토리얼 비주얼',
        'trends.meta.archive_prefix': '비주얼 인텔리전스 아카이브',
        'trends.tags.texture': '텍스처',
        'trends.tags.volume': '볼륨',
        'trends.tags.nostalgia': '노스탤지어',
        'trends.tags.fluidity': '유동성',
        'trends.meta.popularity_label': '인기도',
        'trends.meta.popularity_value': '높음',
        'trends.meta.context_label': '컨텍스트',
        'trends.meta.context_value': '미학',
        'trends.cta.explore': '컬렉션 둘러보기',

        // Community
        'community.title_bg': '컬렉티브',
        'community.title': '더 서클',
        'community.desc': '큐레이터와 크리에이터가 영감을 나누는 글로벌 스타일 네트워크.',
        'community.share': '스타일 공유하기',
        'community.follow': '팔로우',
        'community.post_desc': '디지털 텍스처와 유기적 실루엣의 교차점을 탐구합니다.',
        'community.stat1': '큐레이터',
        'community.stat2': '공유된 룩',
        'community.stat3': '글로벌 허브',
        'community.stat4': '상태',
        'community.filters.all': '전체',
        'community.filters.trending': '트렌딩',
        'community.filters.following': '팔로잉',
        'community.filters.atelier': '디지털 아틀리에',
        'community.filters.subculture': '네오 서브컬처',
        'community.contributor': '컨트리뷰터',
        'community.alt.look': '커뮤니티 룩',
        'community.stat3.value': '서울',
        'community.stat4.value': '라이브',
        'community.tags.cyber': '사이버',
        'community.tags.tech': '테크',
        'community.tags.vintage': '빈티지',
        'community.tags.minimal': '미니멀',
        'community.tags.tailoring': '테일러링',
        'community.tags.neo': '네오',
        'community.tags.utility': '유틸리티',
        'community.tags.outdoor': '아웃도어',
        'community.tags.abstract': '추상',
        'community.tags.ethereal': '에테리얼',
        'community.tags.monochrome': '모노크롬',
        'community.tags.avant': '아방',
        'community.tags.layering': '레이어링',
        'community.tags.urban': '어반',
        'community.tags.core': '코어',
        'community.tags.future': '퓨처',
        'community.tags.graphic': '그래픽',
        'community.tags.street': '스트리트',

        // Profile
        'profile.settings': '에디토리얼 설정',
        'profile.node': '프라이빗 아카이브 노드 042',
        'profile.stat.reach': '리치',
        'profile.stat.curation': '큐레이션',
        'profile.stat.assets': '에셋',
        'profile.stat.archive': '아카이브',
        'profile.header.badge': 'FreeStyle 프로필',
        'profile.header.title': '내 아카이브',
        'profile.header.subtitle': '코디를 저장하고 공유해보세요.',
        'profile.bio.line1': '디지털 크래프트와 물리적 형태의 교차점을 탐구합니다.',
        'profile.bio.line2_prefix': '특화 스타일은',
        'profile.bio.line2_connector': '와',
        'profile.bio.line2_suffix': '에 집중합니다.',
        'profile.bio.focus1': '어반 그런지',
        'profile.bio.focus2': '네오 사이버',
        'profile.tabs.archived': '아카이브',
        'profile.tabs.curations': '내 큐레이션',
        'profile.tabs.saved': '저장한 에셋',
        'profile.post.view_asset': '에셋 보기',
        'profile.post.node': '비주얼 아카이브 노드 // 2026',
        'profile.post.title_prefix': '아카이브',
        'profile.alt.avatar': '프로필 사진',
        'profile.archive.label': '아카이브',
        'profile.empty.archive': '아직 저장된 코디가 없어요.',
        'profile.empty.assets': '아직 저장된 에셋이 없어요.',
        'profile.delete': '삭제',
        'profile.share.copy': '링크 복사',
        'profile.share.copied': '복사됨',
        'profile.search.archive_placeholder': '코디 이름 검색',
        'profile.search.asset_placeholder': '에셋 이름 검색',
        'profile.filter.all': '전체 카테고리',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children, initialLanguage }: { children: ReactNode; initialLanguage?: Language }) {
    const [language, setLanguage] = useState<Language>(() => readInitialLanguage(initialLanguage));

    useEffect(() => {
        document.documentElement.lang = language;
        try {
            window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
        } catch {
            // Ignore storage failures and keep the in-memory preference.
        }

        document.cookie = `${LANGUAGE_COOKIE_KEY}=${language}; path=/; max-age=31536000; samesite=lax`;
    }, [language]);

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['en']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
